feat(organization): support organization
swpu-acm/online-judge pull request #10
Opened 2024-11-27 15:33 UTC by K0nnyaku

add organization

2024-11-28 00:57 UTC, HsiangNianian approved these changes

2024-11-28 03:29 UTC, K0nnyaku commented
@fu050409

2024-11-28 07:48 UTC, fu050409 requested changes

2024-11-28 07:48 UTC, fu050409 commented on src/utils/organization.rs
> +            owner: vec![],
Consider use:

```suggestion
            owner: vec![org.creator.clone()],
```

2024-11-28 07:48 UTC, fu050409 commented on src/models/organization.rs
> +    pub creator: Thing,
```suggestion
    pub creator: &'data str,
```

`Thing` is hard to deserialize through JSON data, consider use borrowed str and then `Thing::from(("account", org.creator))`to void this.

2024-11-28 07:48 UTC, fu050409 commented on src/routes/index.rs
> +use super::organization;
Have you formmatted the code? I think here should a line break.

2024-11-28 10:08 UTC, fu050409 commented
@K0nnyaku Mark this pull request as ready after all changes emitted.

2024-11-28 11:00 UTC, HsiangNianian commented
WHY "feat(WIP)"

2024-11-28 11:42 UTC, fu050409 commented
> WHY "feat(WIP)"

Conventional standard, uses `type(WIP)` or tagged with `WIP` tag. If you just want to test a new idea and you are not sure the pull request is intend to be merged, mark your pull request as draft instead of `WIP`.

2024-11-28 13:31 UTC, fu050409 approved these changes

2024-11-28 13:31 UTC, merged

2024-11-29 03:58 UTC, HsiangNianian commented
> > WHY "feat(WIP)"
> 
> Conventional standard, uses `type(WIP)` or tagged with `WIP` tag. If you just want to test a new idea and you are not sure the pull request is intend to be merged, mark your pull request as draft instead of `WIP`.
> 

Where is the "Conventional standard"