feat(org): suport get, remove, add, update
swpu-acm/online-judge pull request #71
Opened 2024-12-24 12:18 UTC by K0nnyaku

2024-12-24 12:25 UTC, fu050409 requested changes

2024-12-24 12:25 UTC, fu050409 commented on .cspell.json
> +        "nnyaku",
What's the matter?

2024-12-24 12:25 UTC, fu050409 commented on src/models/organization.rs
> +use std::vec;
Aah?

2024-12-24 12:25 UTC, fu050409 commented on src/models/organization.rs
> +    pub name: String,
Use reference instead of owned string to improve performance if this is provided by user.

2024-12-24 12:25 UTC, fu050409 commented on .zsh_history
> +cargo test
Are you sure?

2024-12-24 12:25 UTC, fu050409 commented on 1000
> +surreal start --user root --pass root --bind 127.0.0.1:5176\
Ha?

2025-01-01 10:00 UTC, fu050409 commented on src/models/organization.rs
> +            members: val.members.iter().map(|x| x.to_string()).collect(),
I think the `x` should be a `Thing`, is just call it to string expected?

2025-01-02 10:38 UTC, K0nnyaku commented on src/models/organization.rs
> +            members: val.members.iter().map(|x| x.to_string()).collect(),
I mistakenly thought that `Thing` implemented the expected `to_string` method, and it has now been changed to 'thing.id.to_row'

2025-01-02 11:03 UTC, fu050409 approved these changes

2025-01-02 11:04 UTC, merged